[tools]
go = "latest"
sqlc = "latest"
golangci-lint = "latest"

[env]
_.file = ".env"

[tasks.start]
run = "go run ./cmd/server/"

[tasks.codegen]
run = """
rm -rf internal/codegen/
sqlc generate -f spec/codegen/sqlc.yaml
"""
description = "Generate code from database and api specs"

[tasks.lint]
run = "golangci-lint run"
description = "Run linter"
