/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package eu.raweceek.codegen.api;

import eu.raweceek.codegen.models.EventDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0-SNAPSHOT")
@Validated
@Tag(name = "Event", description = "the Event API")
public interface EventsApi {

    /**
     * GET /events
     *
     * @return List of events (status code 200)
     */
    @Operation(
        operationId = "eventsGet",
        tags = { "Event" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of events", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EventDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/events",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<EventDto>> eventsGet(
        
    );


    /**
     * GET /events/next
     *
     * @return Next event by startTime (status code 200)
     */
    @Operation(
        operationId = "eventsNextGet",
        tags = { "Event" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Next event by startTime", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/events/next",
        produces = { "application/json" }
    )
    
    ResponseEntity<EventDto> eventsNextGet(
        
    );

}
