// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const countSessionsThisWeek = `-- name: CountSessionsThisWeek :one
select count(*) from sessions
where date_trunc('week', start_time) = date_trunc('week', current_date)
`

func (q *Queries) CountSessionsThisWeek(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsThisWeek)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNextSession = `-- name: GetNextSession :one
select id, summary, location, start_time from sessions
where start_time > now()
order by start_time
limit 1
`

func (q *Queries) GetNextSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRow(ctx, getNextSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Summary,
		&i.Location,
		&i.StartTime,
	)
	return i, err
}
