version: "2"

sql:
  - name: raweceek
    engine: postgresql
    schema: schema.sql
    queries: queries.sql
    gen:
      go:
        package: db
        out: ../internal/generated/db
        sql_package: pgx/v5
