/* tslint:disable */
/* eslint-disable */
/**
 * Rawe Ceek API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SessionDto,
} from '../models/index';
import {
    SessionDtoFromJSON,
    SessionDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class SessionApi extends runtime.BaseAPI {

    /**
     */
    async sessionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SessionDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SessionDtoFromJSON));
    }

    /**
     */
    async sessionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SessionDto>> {
        const response = await this.sessionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async sessionsNextGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sessions/next`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionDtoFromJSON(jsonValue));
    }

    /**
     */
    async sessionsNextGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionDto> {
        const response = await this.sessionsNextGetRaw(initOverrides);
        return await response.value();
    }

}
