/* tslint:disable */
/* eslint-disable */
/**
 * Rawe Ceek API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI {

    /**
     * Returns the health status of the service
     */
    async systemHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/system/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns the health status of the service
     */
    async systemHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.systemHealthGetRaw(initOverrides);
    }

}
